version: '3.7'

x-common-variables: &common-variables
  NODE_ENV: production
  RACK_ENV: production
  SSR: 'true'

  API_PORT: 4002
  APPLICATION_PORT: 4003

  CLIENT_SIDE_API_BASE_URL: /api
  SERVER_SIDE_API_BASE_URL: http://api:4002/api
  PHOTO_BASE_URL: ''

  STAFF_PHOTOS_PATH: /public/photos
  STAFF_PHOTOS_CACHE_PATH: /tmp/photos
  CARRIERWAVE_PUBLIC_PATH: /public/


services:
  web:
    restart: always
    build: docker/web
    image: "staff_web:${TAG}"
    ports:
      - '4000:80'
    volumes:
      - 'photos:/public/photos'
    depends_on:
      - app
      - api
  app:
    restart: always
    build: docker/app
    image: "staff_app:${TAG}"
    environment: *common-variables
    ports:
      - '4003:4003'
    depends_on:
      - api
  api:
    restart: always
    build: docker/api
    image: "staff_api:${TAG}"
    environment: *common-variables
    ports:
      - '4002:4002'
    volumes:
      - 'photos:/public/photos'
    depends_on:
      - db
    command: puma -C /api/config/puma.rb
  db:
    restart: always
    build: docker/db
    image: "staff_db:${TAG}"
    volumes:
      - 'db_data:/data/db'
      - type: bind
        source: /var/staff/backup
        target: /backup
volumes:
  db_data:
  photos:
