version: '3.7'

x-common-variables: &common-variables
  NODE_ENV: production
  RACK_ENV: production
  SSR: 'true'

  API_PORT: 4002
  APPLICATION_PORT: 4003

  CLIENT_SIDE_API_BASE_URL: /api
  SERVER_SIDE_API_BASE_URL: http://api:4002/api
  PHOTO_BASE_URL: ''

  STAFF_PHOTOS_PATH: /public/photos
  STAFF_PHOTOS_CACHE_PATH: /tmp/photos
  CARRIERWAVE_PUBLIC_PATH: /public/


services:
  web:
    restart: always
    image: staff_web
    build: docker/web
    ports:
      - '4000:80'
    volumes:
      - 'photos:/public/photos'
    depends_on:
      - app
      - api
  app:
    restart: always
    image: staff_app
    build: docker/app
    environment: *common-variables
    ports:
      - '4003:4003'
    depends_on:
      - api
  api:
    restart: always
    image: staff_api
    build: docker/api
    environment: *common-variables
    ports:
      - '4002:4002'
    volumes:
      - 'photos:/public/photos'
    depends_on:
      - db
    command: puma -C /api/config/puma.rb
  import:
    build: docker/api
    image: staff_api
    environment: *common-variables
    env_file:
      - docker/import/.env
    volumes:
      - 'photos:/public/photos'
      - type: bind
        source: /var/staff/import
        target: /import
      - type: tmpfs
        target: /tmp/photos
    depends_on:
      - db
  db:
    restart: always
    image: staff_db
    build: docker/db
    volumes:
      - 'db_data:/data/db'
volumes:
  db_data:
  photos:
